version: '3.8'
volumes:
  postgresdb:
services:
  postgres:
    build:
      context: ./postgres
    image: postgres
    container_name: "postgres"
    tty: true
    restart: always
    user: root
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post
      - POSTGRES_DB=eventstore
    volumes:
      - postgresdb:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d
  pgadmin:
    build:
      context: ./pgadmin
    image: pgadmin
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_SERVER_JSON_FILE=/pgadmin/servers.json
      - PGADMIN_PREFERENCES_JSON_FILE=/pgadmin/preferences.json
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
      - PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED=False
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
    volumes:
      - ./pgadmin/storage:/root/storage
      - ./pgadmin/servers.json:/pgadmin/servers.json
      - ./pgadmin/preferences.json:/pgadmin/preferences.json
    user: root
    restart: always
    entrypoint: /entrypoint.sh
    depends_on:
      - postgres